### Análise Exploratória de Dados (EDA)

In [9]:
# O Senac possui um departamento de jogos. O problema: Com a mudança de gerações e perfil dos jogadores, o time de jogos tem diversas dúvidas. 
#Por exemplo: que tipo de jogo é mais comercial, qual plataforma está sendo mais utilizada, que tipo de jogos podemos lançar (produto).

In [3]:
import pandas as pd

In [6]:
import pandas as pd
df = pd.read_csv('datasets/Video Games Sales.csv')




1.   Entrar no Kaggle
2.   Escolher um Dataset
1.   Importar o pandas
1.   Usar funções (head(), tail(), Series(tupla, lista, dict))
2.   Estatisticas Descritiva: describe(), mostrar uma coluna, fatiar, columns, info(), len()
2.   Outros (loc(), iloc(), isnull(), fillna(),isna(), pivot(), drop(), lambda(), mean(), median(), mode()

In [7]:
df.tail()

,index,Rank,Game Title,Platform,Year,Genre,Publisher,North America,Europe,Japan,Rest of World,Global,Review
1902,1902,1903,Lizzie McGuire 2: Lizzie Diaries,GBA,2004.0,Action,Disney Interactive Studios,0.60,0.22,0.00,0.01,0.83,55.00
1903,1903,1904,Xenoblade Chronicles,Wii,2010.0,Role-Playing,Nintendo,0.39,0.22,0.16,0.07,0.83,91.74
1904,1904,1905,SingStar Abba,PS3,2008.0,Misc,Sony Computer Entertainment,0.25,0.44,0.00,0.14,0.83,73.00
1905,1905,1906,FIFA Soccer World Championship,PS2,2000.0,Sports,Electronic Arts,0.27,0.21,0.28,0.07,0.83,73.00
1906,1906,1907,WWE SmackDown vs. Raw 2011,X360,2010.0,Fighting,THQ,0.42,0.32,0.00,0.09,0.83,82.00

In [8]:
df.head()

,index,Rank,Game Title,Platform,Year,Genre,Publisher,North America,Europe,Japan,Rest of World,Global,Review
0,0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,40.43,28.39,3.77,8.54,81.12,76.28
1,1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,91.00
2,2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,14.50,12.22,3.63,3.21,33.55,82.07
3,3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,14.82,10.51,3.18,3.01,31.52,82.65
4,4,5,Tetris,GB,1989.0,Puzzle,Nintendo,23.20,2.26,4.22,0.58,30.26,88.00

In [9]:
df.describe()

,index,Rank,Year,North America,Europe,Japan,Rest of World,Global,Review
count,1907.0000,1907.0000,1878.000000,1907.000000,1907.000000,1907.000000,1907.000000,1907.000000,1907.000000
mean,953.0000,954.0000,2003.766773,1.258789,0.706675,0.317493,0.206471,2.489240,79.038977
std,550.6478,550.6478,5.895369,1.956560,1.148904,0.724945,0.343093,3.563159,10.616899
min,0.0000,1.0000,1983.000000,0.000000,0.000000,0.000000,0.000000,0.830000,30.500000
25%,476.5000,477.5000,2000.000000,0.510000,0.230000,0.000000,0.060000,1.110000,74.000000
50%,953.0000,954.0000,2005.000000,0.810000,0.440000,0.020000,0.130000,1.530000,81.000000
75%,1429.5000,1430.5000,2008.000000,1.375000,0.810000,0.300000,0.220000,2.540000,86.230000
max,1906.0000,1907.0000,2012.000000,40.430000,28.390000,7.200000,8.540000,81.120000,97.000000

In [10]:
resumo = df.describe()


# Faça um relatório com a definição das variáveis (estatistico)

*   Variavel Quantitativa (continua ou discreta)
*   Variavel Qualitativa (nominal ou ordinal)

In [11]:
df.mean

<bound method DataFrame.mean of       index  Rank                        Game Title Platform    Year  \
0         0     1                        Wii Sports      Wii  2006.0
1         1     2                 Super Mario Bros.      NES  1985.0
2         2     3                    Mario Kart Wii      Wii  2008.0
3         3     4                 Wii Sports Resort      Wii  2009.0
4         4     5                            Tetris       GB  1989.0
...     ...   ...                               ...      ...     ...
1902   1902  1903  Lizzie McGuire 2: Lizzie Diaries      GBA  2004.0
1903   1903  1904              Xenoblade Chronicles      Wii  2010.0
1904   1904  1905                     SingStar Abba      PS3  2008.0
1905   1905  1906    FIFA Soccer World Championship      PS2  2000.0
1906   1906  1907        WWE SmackDown vs. Raw 2011     X360  2010.0

             Genre                    Publisher  North America  Europe  Japan  \
0           Sports                     Nintendo          40.43   28.39   3.77
1         Platform                     Nintendo          29.08    3.58   6.81
2           Racing                     Nintendo          14.50   12.22   3.63
3           Sports                     Nintendo          14.82   10.51   3.18
4           Puzzle                     Nintendo          23.20    2.26   4.22
...            ...                          ...            ...     ...    ...
1902        Action   Disney Interactive Studios           0.60    0.22   0.00
1903  Role-Playing                     Nintendo           0.39    0.22   0.16
1904          Misc  Sony Computer Entertainment           0.25    0.44   0.00
1905        Sports              Electronic Arts           0.27    0.21   0.28
1906      Fighting                          THQ           0.42    0.32   0.00

      Rest of World  Global  Review
0              8.54   81.12   76.28
1              0.77   40.24   91.00
2              3.21   33.55   82.07
3              3.01   31.52   82.65
4              0.58   30.26   88.00
...             ...     ...     ...
1902           0.01    0.83   55.00
1903           0.07    0.83   91.74
1904           0.14    0.83   73.00
1905           0.07    0.83   73.00
1906           0.09    0.83   82.00

[1907 rows x 13 columns]>

In [12]:
df.median

<bound method DataFrame.median of       index  Rank                        Game Title Platform    Year  \
0         0     1                        Wii Sports      Wii  2006.0
1         1     2                 Super Mario Bros.      NES  1985.0
2         2     3                    Mario Kart Wii      Wii  2008.0
3         3     4                 Wii Sports Resort      Wii  2009.0
4         4     5                            Tetris       GB  1989.0
...     ...   ...                               ...      ...     ...
1902   1902  1903  Lizzie McGuire 2: Lizzie Diaries      GBA  2004.0
1903   1903  1904              Xenoblade Chronicles      Wii  2010.0
1904   1904  1905                     SingStar Abba      PS3  2008.0
1905   1905  1906    FIFA Soccer World Championship      PS2  2000.0
1906   1906  1907        WWE SmackDown vs. Raw 2011     X360  2010.0

             Genre                    Publisher  North America  Europe  Japan  \
0           Sports                     Nintendo          40.43   28.39   3.77
1         Platform                     Nintendo          29.08    3.58   6.81
2           Racing                     Nintendo          14.50   12.22   3.63
3           Sports                     Nintendo          14.82   10.51   3.18
4           Puzzle                     Nintendo          23.20    2.26   4.22
...            ...                          ...            ...     ...    ...
1902        Action   Disney Interactive Studios           0.60    0.22   0.00
1903  Role-Playing                     Nintendo           0.39    0.22   0.16
1904          Misc  Sony Computer Entertainment           0.25    0.44   0.00
1905        Sports              Electronic Arts           0.27    0.21   0.28
1906      Fighting                          THQ           0.42    0.32   0.00

      Rest of World  Global  Review
0              8.54   81.12   76.28
1              0.77   40.24   91.00
2              3.21   33.55   82.07
3              3.01   31.52   82.65
4              0.58   30.26   88.00
...             ...     ...     ...
1902           0.01    0.83   55.00
1903           0.07    0.83   91.74
1904           0.14    0.83   73.00
1905           0.07    0.83   73.00
1906           0.09    0.83   82.00

[1907 rows x 13 columns]>

In [13]:
df.mode

<bound method DataFrame.mode of       index  Rank                        Game Title Platform    Year  \
0         0     1                        Wii Sports      Wii  2006.0
1         1     2                 Super Mario Bros.      NES  1985.0
2         2     3                    Mario Kart Wii      Wii  2008.0
3         3     4                 Wii Sports Resort      Wii  2009.0
4         4     5                            Tetris       GB  1989.0
...     ...   ...                               ...      ...     ...
1902   1902  1903  Lizzie McGuire 2: Lizzie Diaries      GBA  2004.0
1903   1903  1904              Xenoblade Chronicles      Wii  2010.0
1904   1904  1905                     SingStar Abba      PS3  2008.0
1905   1905  1906    FIFA Soccer World Championship      PS2  2000.0
1906   1906  1907        WWE SmackDown vs. Raw 2011     X360  2010.0

             Genre                    Publisher  North America  Europe  Japan  \
0           Sports                     Nintendo          40.43   28.39   3.77
1         Platform                     Nintendo          29.08    3.58   6.81
2           Racing                     Nintendo          14.50   12.22   3.63
3           Sports                     Nintendo          14.82   10.51   3.18
4           Puzzle                     Nintendo          23.20    2.26   4.22
...            ...                          ...            ...     ...    ...
1902        Action   Disney Interactive Studios           0.60    0.22   0.00
1903  Role-Playing                     Nintendo           0.39    0.22   0.16
1904          Misc  Sony Computer Entertainment           0.25    0.44   0.00
1905        Sports              Electronic Arts           0.27    0.21   0.28
1906      Fighting                          THQ           0.42    0.32   0.00

      Rest of World  Global  Review
0              8.54   81.12   76.28
1              0.77   40.24   91.00
2              3.21   33.55   82.07
3              3.01   31.52   82.65
4              0.58   30.26   88.00
...             ...     ...     ...
1902           0.01    0.83   55.00
1903           0.07    0.83   91.74
1904           0.14    0.83   73.00
1905           0.07    0.83   73.00
1906           0.09    0.83   82.00

[1907 rows x 13 columns]>

In [16]:
from pathlib import Path
import pandas as pd

In [36]:
df.columns

Index(['index', 'Rank', 'Game Title', 'Platform', 'Year', 'Genre', 'Publisher',
       'North America', 'Europe', 'Japan', 'Rest of World', 'Global',
       'Review'],
      dtype='object')

In [47]:
#plataformas está sendo mais utilizadas
plataforma = df['Platform'].value_counts()
plataforma

Platform
PS2     372
PS      223
X360    219
PS3     202
Wii     161
DS      149
GBA      75
XB       72
PC       71
PSP      63
NES      60
N64      57
GC       55
GB       48
SNES     41
3DS      15
GEN      11
DC        6
SAT       3
WiiU      2
SCD       1
PSV       1
Name: count, dtype: int64

In [17]:
print("CWD:", Path().resolve())

CWD: C:\Users\cassio49734596\Desktop\phyton_data_cience

In [18]:
print([p.name for p in Path('datasets').glob('*.csv')])

['dataset_ruido.csv', 'tempo_salarios _incompleto.csv', 'tempo_salarios.csv', 'Video Games Sales.csv']

In [19]:
# Caminho absoluto — use r'' para não escapar a barra invertida
df = pd.read_csv(r"C:\Users\cassio49734596\Desktop\phyton_data_cience\datasets\Video Games Sales.csv")